### ISSUE TITLE
How to keep up with remote changes

### ISSUE THREAD

**Issue by Jacco** [reactjs/nl.reactjs.org#41]
I found that at a certain moment in time a snapshot of the original english version was made. I don't know exactly when, but I found that for example this commit:

https://github.com/reactjs/reactjs.org/commit/5c371e5e3fd8f92e1d06dfdf1f28edc50fb5d83f

Was not in that base. This means that after we have finished translating we need to follow the trail of all content commits from the snapshot time until now...

Is there a smarter way to do this?

**Comment by Jacco** [comment]
I think it might be because we are adding "linefeeds" to articles. I have watched the repositories for a few other languages and they still get sync PRs. The sync system automatically sends PRs with commit for every file. These commits will first look at which lines changed in the english version, then create a commit for that file using the dutch version replacing the updated lines with the new english version based on **line number** I think thjs is why we do not get sync PRS any more. We should never accepts any PR where the number of lines of the article changes.

**Comment by Keraito** [comment]
@tesseralis Could you enlighten us here whether the findings of @Jacco are correct? And if so, what the best course of action is, besides his plan of action, to get back in sync again with the main translations?

**Comment by Jacco** [comment]
It might be the case that linefeed do not matter but I also saw some occurences of *notes* where a linefeed was added inside a note, but the extra line did not have a >, meaning it would create two note sections.

Maybe our repo is no longer merged because it is not compliant for that reason?

The guess then would be that we no longer get synced because we are not merged.

**Comment by Jacco** [comment]
Closing
